FROM node:18 AS build

WORKDIR /app
# Копируем package.json и т.д. (из папки frontend)
COPY ./frontend/package*.json ./
RUN npm install

# Копируем остальной фронтенд-код
COPY ./frontend/ ./
RUN npm run build

# --- Финальный stage: Nginx
FROM nginx:alpine

# Копируем Nginx конфигурацию
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Копируем фронтенд-ресурсы
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]